on: push

name: ci

jobs:
  ci:
    runs-on: windows-${{matrix.os}}
    strategy:
      matrix:
        os:
        - latest
        - 2022
    steps:
      - run: |
          wsl --help
          
          wsl -l -v
          
          wsl uname -a
          
          wsl -d ubuntu
          
          get-command wsl
          get-command bash
          
          $PSVersionTable
