on: push

name: ci

jobs:
  ci:
    runs-on: windows-${{matrix.os}}
    strategy:
      matrix:
        os:
        # - latest
        - 2022
    steps:
      - run: |
          wsl --help
          
          wsl -l -v
          
          wsl uname -a
          
          wsl -d ubuntu
          
          get-command wsl
          get-command bash
          
          $PSVersionTable
        continue-on-error: true  
      - uses: Vampire/setup-wsl@v1
      - run: wsl -l -v
      - run: pwd
        shell: powershell
      - run: |
          $GITHUB_RELEASE = "github.com"
          $kernelversion='5.13.0'
          curl.exe -fL https://${GITHUB_RELEASE}/khs1994/WSL2-Linux-Kernel/releases/download/${kernelversion}-microsoft-standard-WSL2/kernel-${kernelversion}-microsoft-standard-WSL2.img -O 
          echo '[wsl2]' > ~/.wslconfig
          echo "kernel=D:\\a\\wsl2\\wsl2\\kernel-${kernelversion}-microsoft-standard-WSL2.img" >> ~/.wslconfig
          ls ~/.wslconfig
          cat ~/.wslconfig
        shell: powershell
      - run: wsl --status
        continue-on-error: true
      - run: wsl --update
        continue-on-error: true
      - run: wsl --set-version debian 2
        continue-on-error: true
