on: push

name: ci

jobs:
  ci:
    runs-on: windows-${{matrix.os}}
    strategy:
      matrix:
        os:
        # - latest
        - 2022
    steps:
      - run: |
          wsl --help
          
          wsl -l -v
          
          wsl uname -a
          
          wsl -d ubuntu
          
          get-command wsl
          get-command bash
          
          $PSVersionTable
        continue-on-error: true  
      - uses: Vampire/setup-wsl@v1
      - run: wsl -l -v
      - run: wsl --status
      - run: wsl --update
        continue-on-error: true
      - run: wsl --set-version debian 2
        continue-on-error: true
