on: push

name: ci

jobs:
  ci:
    runs-on: windows-latest
    steps:
      - run: |
          wsl --help
          
          wsl -l -v
          
          wsl uname -a
          
          wsl -d ubuntu
          
          get-command wsl
          get-command bash
          
          $PSVersionTable
